### ISSUE TITLE
Town Map in both Key Items and Goods at the same time

### ISSUE THREAD

**Issue by BeepyBoop1987** [ShrineFox/EarthBound-Mod-Menu#11]
The title basically describes it lol. I found it originally when I first played around with the mod, but I just tested it again for the sake of being sure, and it's consistent. Though I completely understand the Town Map being one of the few items where something like this could happen, since it's probably one of the easiest items to miss or forget about when playing Earthbound, especially after you play it as often as we all do, just due to not needing it anymore.

**Comment by ShrineFox** [comment]
Thanks for mentioning this! You're right, I think that's exactly what happened haha. I forgot to ever check if it worked properly since it's not part of the main quest line. I'll see about fixing this in the next update!
